name: Create Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current time
        id: time
        run: echo "datetime=$(date +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "${{ github.ref_name }}+${{ steps.time.outputs.datetime }}"
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          prerelease: true
